# Generated by Django 4.1.4 on 2024-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
    ]
