# Generated by Django 4.1.4 on 2024-09-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_alter_presentation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['created_at'], 'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
    ]
