#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py collectstatic --noinput
python manage.py import_presentations /app/server/presentations/data/prezis.json
python manage.py migrate

exec gunicorn --bind 0.0.0.0:"${PORT:-8000}" config.wsgi:application
