name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Heroku container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Set Heroku stack to Docker
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku stack:set container -a prezi-presentations

    - name: Build Docker image
      run: |
        docker build -f ./backend/docker/production/django/Dockerfile -t registry.heroku.com/prezi-presentations/web .

    - name: Push to Heroku
      run: |
        docker push registry.heroku.com/prezi-presentations/web

    - name: Set environment variables
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        DJANGO_ADMIN_URL: ${{ secrets.DJANGO_ADMIN_URL }}
      run: |
        heroku config:set DJANGO_SECRET_KEY=DJANGO_SECRET_KEY DATABASE_URL=$DATABASE_URL DJANGO_ALLOWED_HOSTS=DJANGO_ALLOWED_HOSTS DJANGO_ADMIN_URL=DJANGO_ADMIN_URL -a prezi-presentations

    - name: Release the image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web -a prezi-presentations
